import fs from 'node:fs/promises';
import path from 'node:path';

import { $, chalk } from 'zx';

import { SUPABASE_PROJECT_ID } from 'supabase';

const comment = `
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file was automatically generated using the command: yarn generate:supabaseTypes
\n`.trimStart();

const supabaseTypesFilePath = path.resolve(__dirname, '..', 'supabase', 'database.types.ts');

async function generateSupabaseTypes() {
  const supabaseTypes =
    await $`npx -y supabase gen types typescript --project-id ${SUPABASE_PROJECT_ID}`
      .quiet()
      .text();

  const supabaseTypesWithComment = comment.concat(supabaseTypes);

  await fs.writeFile(supabaseTypesFilePath, supabaseTypesWithComment);

  console.log(chalk.blue('Supabase types generated successfully!'));
}

generateSupabaseTypes();
